### PR TITLE
Add UnmarshalHostPrivateKey helper function

### PR DESCRIPTION
**Pull request by johnmaguire**

### CODE REVIEW

**Review by brad-defined — APPROVED** [review]

**Comment by nbrownus** [comment]
This is fine, I was curious if we would want to know the type so we could assert any incompatible type situations

**Comment by johnmaguire** [comment]
@nbrownus What do you mean by "any incompatible type situations"? This is just a wrapper function around some existing unmarshal functions. `PrivateKey.Unwrap()` gives you the underlying type.

**Comment by nbrownus** [comment]
I haven't reviewed the usage of the function but I see we are losing context on which curve is contained in the pem bytes.

If that curve doesn't match the public keys curve then we have some problems and the crypto might not fail (ed25519 mixed with x25519)

**Comment by johnmaguire** [comment]
@nbrownus NewPrivateKey returns an implementation of Ed25519PrivateKey or P256PrivateKey. The PrivateKey interface Unwrap() returns the underlying key (which can be type-matched.)

**Comment by johnmaguire** [comment]
https://github.com/DefinedNet/dnapi/blob/9f2241dc2c59aadcf321550ceab31a2a7515f525/keys/keys.go#L110-L119

**Pull request merged**
